### ISSUE TITLE
Missing packages in epel repo

### ISSUE THREAD

**Issue by w1ldptr** [ctrautma/RHEL_NIC_QUALIFICATION#1]
Packages python-twisted-core,  python-zope-interface, groff are not in repo anymore.
Python packages were probably removed because of this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1363962

**Comment by ctrautma** [comment]
Can you try enabling the channel rhel-7-server-optional-rpms and see if that fixes this?

**Comment by w1ldptr** [comment]
Indeed, all of the missing packages are in rhel-7-server-optional-rpms repo.
