### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by ddaya** [ctrautma/RHEL_NIC_QUALIFICATION#5]
Setup the Device Under Test (DUT), Open vSwitch -> Add the packages we need

# subscription-manager repos --enable=rhel-7-fast-datapath-rpms
Error: 'rhel-7-fast-datapath-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.

=> "rhel-7-fast-datapath-htb-rpms" exist and not "rhel-7-fast-datapath-rpms"

# subscription-manager repos --enable=rhel-7-server-rhv-4-mgmt-agent-rpms
Error: 'rhel-7-server-rhv-4-mgmt-agent-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.

=> Cannot find "rhel-7-server-rhv-4-mgmt-agent-rpms" in "yum repolist all"

**Comment by ctrautma** [comment]
Thanks, I'll get to the bottom of this. These used to work so something has changed in the repo list.

**Comment by chaudron** [comment]
Did a quick clean setup and I can add those repositories. Can you try subscription-manager repos --list, to see if they are there. If they are not you need to get in touch with your Red Hat representative to get you access to those repositories.

**Comment by ctrautma** [comment]
Going to mark as closed. Please re-open if this is still an issue.
