### ISSUE TITLE
OVS functional qualification and IMG_GUEST

### ISSUE THREAD

**Issue by felix-cavium** [ctrautma/RHEL_NIC_QUALIFICATION#6]
In rh_nic_cert.tar, the script rh_nic_cert.sh defines IMG_GUEST as:

    http://netqe-bj.usersys.redhat.com/share/vms/rhel7.4.qcow2

But the FQDN in that URL is not in the Internet, and so this error happens:

# wget http://netqe-bj.usersys.redhat.com/share/vms/rhel7.4.qcow2                                                     
--2018-01-28 15:19:18--  http://netqe-bj.usersys.redhat.com/share/vms/rhel7.4.qcow2                                                             
Resolving netqe-bj.usersys.redhat.com (netqe-bj.usersys.redhat.com)... failed: Name or service not known.                                        
wget: unable to resolve host address ‘netqe-bj.usersys.redhat.com’

I was able to resolve it by connecting to Red Hat's network by VPN (since I am a Red Hat partner engineer, I was granted VPN access).

Can you put that rhel7.4.qcow2 image in a publicly-accessible file server so that it won't be necessary to VPN to Red Hat?

**Comment by ctrautma** [comment]
Not sure how this was missed. I will make sure to upload the image and have the script changed.

**Comment by ctrautma** [comment]
We have a change to resolve this. If you get time please pull down the latest rh_nic_cert.tar file and retest.

**Comment by felix-cavium** [comment]
We confirm that this issue is resolved.  Thanks.
